<?php

echo view('admin/pincode/list', [
    'page_title' => $page_title ?? 'Bluedart Air Pincodes',
    'code' => $code ?? [],
    'count' => $count ?? 0,
    'links' => $links ?? '',
    'permission' => $permission ?? ($GLOBALS['permission'] ?? []),
    'selected_pincode' => $selected_pincode ?? '',
    'import_title' => 'Import Bluedart Air',
    'sample_title' => 'Sample Format',
    'sample_headers' => [
        'CPINCODE',
        'CAREA',
        'CAREADESC',
        'CBRANCH',
        'CSTATE',
        'PURCHASE ZONE',
        'CAPESERV',
        'APEX_SERV_LOC_INB',
        'APEX_SERV_LOC_OUTB',
        'CTCLSERV',
        'CAPTDD12',
        'APEX TAT',
        'EDL_APEX',
        'EDL_APEX_DIST',
    ],
    'sample_rows' => [
        ['700000', 'CCU', 'KOLKATA', 'ERO', 'EAST REGIONAL OFFICE', 'E2', 'E2', 'BOM', 'AVN', 'ERO', 'PST', '168', 'No', '0'],
        ['700004', 'CCU', 'KOLKATA', 'BTR', 'B T ROAD SERVICE CENTRE', 'E2', 'E2', 'DEL', 'SGZ', 'ERO', 'PST', '168', 'YES', '10'],
    ],
    'columns' => [
        ['label' => 'CPINCODE', 'value' => 'pincode'],
        ['label' => 'CAREA', 'value' => 'area'],
        ['label' => 'CAREADESC', 'value' => 'area_desc'],
        ['label' => 'CBRANCH', 'value' => 'branch'],
        ['label' => 'CSTATE', 'value' => 'state'],
        ['label' => 'PURCHASE ZONE', 'value' => 'purchase_zone'],
    ],
    'search_placeholder' => 'Search By Pincode',
    'search_route' => 'admin/pincode/bluedart_air',
    'import_route' => 'admin/pincode/import_bluedart_air',
    'delete_route' => 'admin/pincode/delete_bluedart_air',
    'export_route' => 'admin/pincode/export_bluedart_air',
]);
