<?php

echo view('admin/pincode/list', [
    'page_title' => $page_title ?? 'Bluedart DP Pincodes',
    'code' => $code ?? [],
    'count' => $count ?? 0,
    'links' => $links ?? '',
    'permission' => $permission ?? ($GLOBALS['permission'] ?? []),
    'selected_pincode' => $selected_pincode ?? '',
    'import_title' => 'Import Bluedart DP',
    'sample_title' => 'Sample Format',
    'sample_headers' => [
        'PINCODE',
        'AREA',
        'AREA DESCRIPTION',
        'LOCATION',
        'LOC DESCRIPTION',
        'BRANCH',
        'STATE',
        'STATE CODE',
        'PURCHASE ZONE',
        'EDL_DP',
        'DP SERVICE',
        'CODE',
        'CODE1',
        'TAT',
    ],
    'sample_rows' => [
        ['111123', 'DEL', 'NEW DELHI', 'DRC', 'DELHI CANTT DELIVERY AGENT', 'SJE', 'DELHI', 'DH', 'A', 'No', 'Both', 'DRC', 'DRC', '24'],
        ['121000', 'FAR', 'FARIDABAD', 'FAO', 'FAR SERVICE CENTRE', 'OKH', 'HARYANA', 'HN', 'A', 'No', 'Both', 'FAO', 'FAO', '24'],
    ],
    'columns' => [
        ['label' => 'Pincode', 'value' => 'pincode'],
        ['label' => 'Area', 'value' => 'area'],
        ['label' => 'Area Description', 'value' => 'area_desc'],
        ['label' => 'Location', 'value' => 'location'],
        ['label' => 'Branch', 'value' => 'branch'],
        ['label' => 'State', 'value' => 'state'],
        ['label' => 'Purchase Zone', 'value' => 'purchase_zone'],
    ],
    'search_placeholder' => 'Search By Pincode',
    'search_route' => 'admin/pincode/bluedart_dp',
    'import_route' => 'admin/pincode/import_bluedart_dp',
    'delete_route' => 'admin/pincode/delete_bluedart_dp',
    'export_route' => 'admin/pincode/export_bluedart_dp',
]);
